apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aks1kodey-d5dd"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aks1kodey-d5dd"
  template:
    metadata:
      labels:
        app: "aks1kodey-d5dd"
    spec:
      containers:
        - name: "aks1kodey-d5dd"
          image: "l5aks.azurecr.io/aks1kodeyd5dd"
          ports:
          - containerPort: 80