apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "petestaks-4175"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "petestaks-4175"
    spec:
      containers:
        - name: "petestaks-4175"
          image: "tesfgdrge.azurecr.io/petestaks"
          ports:
          - containerPort: 80