apiVersion : apps/v1
kind: Deployment
metadata:
  name: "ajayaks12-9e8f"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "ajayaks12-9e8f"
  template:
    metadata:
      labels:
        app: "ajayaks12-9e8f"
    spec:
      containers:
        - name: "ajayaks12-9e8f"
          image: "l5aks.azurecr.io/ajayaks129e8f"
          ports:
          - containerPort: 80