apiVersion : apps/v1
kind: Deployment
metadata:
  name: "akskodey-e6c0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "akskodey-e6c0"
  template:
    metadata:
      labels:
        app: "akskodey-e6c0"
    spec:
      containers:
        - name: "akskodey-e6c0"
          image: "akskodeyacr32w12.azurecr.io/akskodeye6c0"
          ports:
          - containerPort: 80