apiVersion : apps/v1
kind: Deployment
metadata:
  name: "akskodey-216f"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "akskodey-216f"
  template:
    metadata:
      labels:
        app: "akskodey-216f"
    spec:
      containers:
        - name: "akskodey-216f"
          image: "akskodeyacr12321.azurecr.io/akskodey216f"
          ports:
          - containerPort: 80