apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aks1kodey-ce34"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aks1kodey-ce34"
  template:
    metadata:
      labels:
        app: "aks1kodey-ce34"
    spec:
      containers:
        - name: "aks1kodey-ce34"
          image: "aks1kodeyacr454321212.azurecr.io/aks1kodeyce34"
          ports:
          - containerPort: 80