apiVersion : apps/v1
kind: Deployment
metadata:
  name: "akskodey-1e7a"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "akskodey-1e7a"
  template:
    metadata:
      labels:
        app: "akskodey-1e7a"
    spec:
      containers:
        - name: "akskodey-1e7a"
          image: "l5aks1511.azurecr.io/akskodey1e7a"
          ports:
          - containerPort: 80