apiVersion: v1
kind: Service
metadata:
    name: "akskodey-0d73"
    labels:
        app: "akskodey-0d73"
spec:
    type: ClusterIP
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "akskodey-0d73"
