apiVersion: v1
kind: Service
metadata:
    name: "petestaks-1fc3"
    labels:
        app: "petestaks-1fc3"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "petestaks-1fc3"