apiVersion: v1
kind: Service
metadata:
    name: "akskodey-359e"
    labels:
        app: "akskodey-359e"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "akskodey-359e"