apiVersion: v1
kind: Service
metadata:
    name: "akskodey-e45e"
    labels:
        app: "akskodey-e45e"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "akskodey-e45e"