on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: aaaatiwarishubregistry.azurecr.io
        username: ${{ secrets.acr_aaaatiwarishubregistry_username }}
        password: ${{ secrets.acr_aaaatiwarishubregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t aaaatiwarishubregistry.azurecr.io/petestaks:${{ github.sha }}
        docker push aaaatiwarishubregistry.azurecr.io/petestaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_petestaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep petest-aks8ff5 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace petest-aks8ff5`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: petest-aks8ff5
        container-registry-url: aaaatiwarishubregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_aaaatiwarishubregistry_username }}
        container-registry-password: ${{ secrets.acr_aaaatiwarishubregistry_password }}
        secret-name: petestaksdockerauth
       
    - uses: azure/k8s-bake@v1
      with:
        renderEngine: 'helm'
        helmChart: aks-helloworld
        releaseName: 'aks-helm-release'
        helm-version: 'latest' 
        silent: 'false'
        overrideFiles: |
          
        overrides: |
          replicas:2
          image.repository:aaaatiwarishubregistry.azurecr.io/petestaks
          image.tag:${{ github.sha }}
          imagePullSecrets:
            -name:petestaksdockerauth
      id: bake

    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: petest-aks8ff5
        manifests: ${{ steps.bake.outputs.manifestsBundle }}
        images: |
          aaaatiwarishubregistry.azurecr.io/petestaks:${{ github.sha }}
        imagepullsecrets: |
          petestaksdockerauth