on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: abhisheaacr.azurecr.io
        username: ${{ secrets.acr_abhisheaacr_username }}
        password: ${{ secrets.acr_abhisheaacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t abhisheaacr.azurecr.io/affasadsa:dasdasdas
        docker push abhisheaacr.azurecr.io/affasadsa:dasdasdas
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_vipulakscluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep vipulakscluster90a5 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace vipulakscluster90a5`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: vipulakscluster90a5
        container-registry-url: abhisheaacr.azurecr.io
        container-registry-username: ${{ secrets.acr_abhisheaacr_username }}
        container-registry-password: ${{ secrets.acr_abhisheaacr_password }}
        secret-name: vipulaksclusdockerauth
       
    - uses: azure/k8s-bake@v1
      with:
        renderEngine: 'helm'
        helmChart: sampleapp
        releaseName: 'aks-helm-release'
        helm-version: 'latest' 
        silent: 'false'
        overrideFiles: |
          sampleapp/override-values.yaml
        overrides: |
          replicas:2
          image.repository:abhisheaacr.azurecr.io/affasadsa
          image.tag:dasdasdas
          imagePullSecrets:
            -name:vipulaksclusdockerauth
      id: bake

    - uses: azure/k8s-deploy@v1
      with:
        namespace: vipulakscluster90a5
        manifests: ${{ steps.bake.outputs.manifestsBundle }}
        images: |
          abhisheaacr.azurecr.io/affasadsa:dasdasdas
        imagepullsecrets: |
          vipulaksclusdockerauth