on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: aaaatiwarishubregistry.azurecr.io
        username: ${{ secrets.acr_aaaatiwarishubregistry_username }}
        password: ${{ secrets.acr_aaaatiwarishubregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t aaaatiwarishubregistry.azurecr.io/aks1kodey:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push aaaatiwarishubregistry.azurecr.io/aks1kodey:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aks1kodey_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aks1kodey9c22 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aks1kodey9c22`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aks1kodey9c22
        container-registry-url: aaaatiwarishubregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_aaaatiwarishubregistry_username }}
        container-registry-password: ${{ secrets.acr_aaaatiwarishubregistry_password }}
        secret-name: aks1kodeydockerauth
       
    - uses: azure/k8s-bake@v1
      with:
        renderEngine: 'helm'
        helmChart: aks-helloworld
        releaseName: 'aks-helm-release'
        helm-version: 'latest' 
        silent: 'false'
        overrideFiles: |
          
        overrides: |
          replicas:2
          image.repository:aaaatiwarishubregistry.azurecr.io/aks1kodey
          image.tag:${{ github.sha }}
          imagePullSecrets:
            -name:aks1kodeydockerauth
      id: bake

    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aks1kodey9c22
        manifests: ${{ steps.bake.outputs.manifestsBundle }}
        images: |
          aaaatiwarishubregistry.azurecr.io/aks1kodey:${{ github.sha }}
        imagepullsecrets: |
          aks1kodeydockerauth
