on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{secrets.aksKodeyacr22312_0766}}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n aksKodeyacr22312 -g aksKodeyacr22312ab16-rg --location "West US 2" --sku Basic --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n aksKodeyacr22312 --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n aksKodeyacr22312 --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n aksKodeyacr22312 --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: akskodeyacr22312.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/." -f  "Dockerfile" -t akskodeyacr22312.azurecr.io/akskodey0766:${{ github.sha }}
        docker push akskodeyacr22312.azurecr.io/akskodey0766:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{secrets.aks_akskodey_kubeConfig}}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep akskodey0766 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace akskodey0766`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: akskodey0766
        container-registry-url: akskodeyacr22312.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: akskodeydockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: akskodey0766
        manifests: |
          ./manifests/deployment-0766.yml
          ./manifests/service-0766.yml
        images: |
          akskodeyacr22312.azurecr.io/akskodey0766:${{ github.sha }}
        imagepullsecrets: |
          akskodeydockerauth