on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{secrets.aksKodeyacr323_55cc}}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n aksKodeyacr323 -g aksKodeyacr32389a7-rg --location "West US" --sku Basic --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n aksKodeyacr323 --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n aksKodeyacr323 --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n aksKodeyacr323 --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: akskodeyacr323.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/." -f  "Dockerfile" -t akskodeyacr323.azurecr.io/akskodey55cc:${{ github.sha }}
        docker push akskodeyacr323.azurecr.io/akskodey55cc:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{secrets.aks_akskodey_kubeConfig}}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep akskodey55cc | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace akskodey55cc`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: akskodey55cc
        container-registry-url: akskodeyacr323.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: akskodeydockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: akskodey55cc
        manifests: |
          ./manifests/deployment-55cc.yml
          ./manifests/service-55cc.yml
          ./manifests/ingress-55cc.yml
        images: |
          akskodeyacr323.azurecr.io/akskodey55cc:${{ github.sha }}
        imagepullsecrets: |
          akskodeydockerauth