on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: ajacr1.azurecr.io
        username: ${{ secrets.acr_ajacr1_username }}
        password: ${{ secrets.acr_ajacr1_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t ajacr1.azurecr.io/asdasd:dasdasds
        docker push ajacr1.azurecr.io/asdasd:dasdasds
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_vipulakscluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep vipulakscluster557a | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace vipulakscluster557a`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: vipulakscluster557a
        container-registry-url: ajacr1.azurecr.io
        container-registry-username: ${{ secrets.acr_ajacr1_username }}
        container-registry-password: ${{ secrets.acr_ajacr1_password }}
        secret-name: vipulaksclusdockerauth
       
    - uses: azure/k8s-bake@v1
      with:
        renderEngine: 'helm'
        helmChart: aks-helloworld
        releaseName: 'aks-helm-release'
        helm-version: 'latest' 
        silent: 'false'
        overrideFiles: |
          aks-helloworld/override-values.yaml
        overrides: |
          replicas:2
          image.repository:ajacr1.azurecr.io/asdasd
          image.tag:dasdasds
          imagePullSecrets:
            -name:vipulaksclusdockerauth
      id: bake

    - uses: azure/k8s-deploy@v1
      with:
        namespace: vipulakscluster557a
        manifests: ${{ steps.bake.outputs.manifestsBundle }}
        images: |
          ajacr1.azurecr.io/asdasd:dasdasds
        imagepullsecrets: |
          vipulaksclusdockerauth