on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n l5scenariotestingrdfd -g l5scenariotestingrdfd86e8-rg --location "West Central US" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n l5scenariotestingrdfd --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n l5scenariotestingrdfd --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n l5scenariotestingrdfd --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: l5scenariotestingrdfd.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t l5scenariotestingrdfd.azurecr.io/akskodey:${{ github.sha }}
        docker push l5scenariotestingrdfd.azurecr.io/akskodey:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_akskodey_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep akskodey8f1b | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace akskodey8f1b`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: akskodey8f1b
        container-registry-url: l5scenariotestingrdfd.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: akskodeydockerauth

    - uses: azure/k8s-bake@v1
      with:
        renderEngine: 'helm'
        helmChart: aks-helloworld
        releaseName: 'aks-helm-release'
        helm-version: 'latest' 
        silent: 'false'
        overrideFiles: |
          
        overrides: |
          replicas:2
          image.repository:l5scenariotestingrdfd.azurecr.io/akskodey
          image.tag:${{ github.sha }}
          imagePullSecrets:
            -name:akskodeydockerauth
      id: bake

    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: akskodey8f1b
        manifests: ${{ steps.bake.outputs.manifestsBundle }}
        images: |
          l5scenariotestingrdfd.azurecr.io/akskodey:${{ github.sha }}
        imagepullsecrets: |
          akskodeydockerauth