on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.aksKodeyacr12321_216f }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n aksKodeyacr12321 -g aksKodeyacr12321b5f8-rg --location "South Central US" --sku Basic --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n aksKodeyacr12321 --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n aksKodeyacr12321 --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n aksKodeyacr12321 --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: akskodeyacr12321.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/." -f  "Dockerfile" -t akskodeyacr12321.azurecr.io/akskodey216f:${{ github.sha }}
        docker push akskodeyacr12321.azurecr.io/akskodey216f:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_akskodey_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep akskodey216f | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace akskodey216f`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: akskodey216f
        container-registry-url: akskodeyacr12321.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: akskodeydockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: akskodey216f
        manifests: |
          ./manifests/deployment-216f.yml
          ./manifests/service-216f.yml
        images: |
          akskodeyacr12321.azurecr.io/akskodey216f:${{ github.sha }}
        imagepullsecrets: |
          akskodeydockerauth